version: '3.8'
services:
  app:
    build:
      args:
        ARG_LINUX_LOCALE: en_US.UTF-8
        ARG_USER_UID: ${ARG_USER_UID}
        ARG_USER_GID: ${ARG_USER_GID}
        ARG_RUBY_VERSION: 3.0.2
      context: .
    depends_on:
      - postgresql
    working_dir: /home/user/base_app
    environment:
      BINDING: 0.0.0.0
      PORT: 3000
      DATABASE_HOST: postgresql
      DATABASE_PORT: 5432
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
    ports:
      - 3000:3000
    tty: true
    volumes:
      - app_local:/usr/local
      - ~/.ssh:/home/user/.ssh
      - ~/.gitconfig:/home/user/.gitconfig
      - ~/.bash_history:/home/user/.bash_history
      - .:/home/user/base_app
  postgresql:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_data:/var/lib/postgresql/data
#    ports:
#      - 5432:5432
volumes:
  app_local:
  postgresql_data:
